document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>Document</title>");
document.writeln("    <link href=\'css/loginRegister.css\' rel=\'stylesheet\' />");
document.writeln("    <link rel=\'stylesheet\' href=\'css/home.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/font_search/iconfont.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/font_heart/iconfont.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/font_shop/iconfont.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/font_close/iconfont.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/font_arrow/iconfont.css\'>");
document.writeln("    <script src=\'jquery-1.11.3/jquery.min.js \'></script>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <header>");
document.writeln("        <div class=\'header-box\'>");
document.writeln("            <!-- 顶部导航栏 -->");
document.writeln("            <div class=\'top-nav\'>");
document.writeln("                <div class=\'top-nav-left\'>");
document.writeln("                    <a href=\'\'>在线客服</a>");
document.writeln("                </div>");
document.writeln("                <!-- 登录 -->");
document.writeln("                <div class=\'top-nav-right\'>");
document.writeln("                    <span id=\'btn\'>欢迎&nbsp;登录/注册</span>");
document.writeln("                    <!-- 登录模块 -->");
document.writeln("                    <div class=\'yinyin\'>");
document.writeln("                        <div class=\'login_register\' id=\'login_register\'>");
document.writeln("                            <!-- 注册 -->");
document.writeln("                            <div id=\'div1\'>");
document.writeln("                                <div id=\'div1_div1\'>");
document.writeln("                                    <!-- 点击x -->");
document.writeln("                                    <div id=\'xImg\' class=\'div1_div11X\'><img src=\'image/x.png\' width=\'15\'></div>");
document.writeln("                                    <script>");
document.writeln("                                        $(function() {");
document.writeln("                                            var xImg = document.getElementById(\'xImg\');");
document.writeln("                                            var yinyin = document.querySelector(\'.yinyin\');");
document.writeln("                                            xImg.onclick = function() {");
document.writeln("                                                yinyin.style.display = \'none\';");
document.writeln("                                            }");
document.writeln("                                        })");
document.writeln("                                    </script>");
document.writeln("                                    <h4>欢迎来到<strong>UA</strong>运动家俱乐部</h4>");
document.writeln("");
document.writeln("                                    <ul class=\'div1_div1ul dialog-title-box e-switch\'>");
document.writeln("                                        <li onclick=\'TurnToRegister()\' class=\'div1_div1ulli1\'>");
document.writeln("                                            <a style=\'color: #000000;font-size: 14px;\' class=\'aP1\'>手机号快捷登录/注册</a>");
document.writeln("                                            <span class=\'hx1\'></span>");
document.writeln("                                        </li>");
document.writeln("                                        <li onclick=\'TurnToLogin()\' class=\'div1_div1ulli2\'>");
document.writeln("                                            <a class=\'aP2\' style=\'font-size: 14px;\'>账号密码登录</a>");
document.writeln("                                            <span class=\'hx2\'></span>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                    <!-- 注册登录跳转 -->");
document.writeln("                                    <script>");
document.writeln("                                        // 登录");
document.writeln("                                        var TurnToLogin = () => {");
document.writeln("                                                document.getElementById(\'div2\').style.display = \'block\';");
document.writeln("                                                document.getElementById(\'div1\').style.display = \'none\';");
document.writeln("                                            }");
document.writeln("                                            // 注册");
document.writeln("                                        var TurnToRegister = () => {");
document.writeln("                                            document.getElementById(\'div1\').style.display = \'block\';");
document.writeln("                                            document.getElementById(\'div2\').style.display = \'none\';");
document.writeln("                                        }");
document.writeln("                                    </script>");
document.writeln("                                    <!-- 表单 -->");
document.writeln("                                    <form id=\'myRegisterForm\'>");
document.writeln("                                        <div class=\'divform\'>");
document.writeln("                                            <div class=\'inputs\'>");
document.writeln("                                                <label class=\'inputs_label1\'>手机号码</label>");
document.writeln("                                                <input id=\'iptPhone\' class=\'inputs_input\' type=\'text\' />");
document.writeln("                                                <p style=\'font-size: 13px;\' id=\'pPhone\'></p>");
document.writeln("                                            </div>");
document.writeln("                                            <br>");
document.writeln("                                            <div class=\'inputs divImgYz\'>");
document.writeln("                                                <label class=\'inputs_label1\'>图形验证码</label>");
document.writeln("                                                <input id=\'iptImg\' class=\'inputs_input imgYz\' type=\'text\' maxlength=\'4\' />");
document.writeln("                                                <!-- 图形验证 -->");
document.writeln("                                                <div id=\'result\' onclick=\'getRanNum()\' class=\'yzImg\'>");
document.writeln("                                                    <span class=\'spanAb\'>A,S,D,C</span>");
document.writeln("                                                    <!-- <img src=\'./image/securityImageLogin.jpg\'/> -->");
document.writeln("                                                </div>");
document.writeln("                                                <p id=\'pImg\' style=\'font-size: 13px;\'></p>");
document.writeln("                                                <script>");
document.writeln("                                                    var result = [];");
document.writeln("");
document.writeln("                                                    function getRanNum() {");
document.writeln("                                                        result = [];");
document.writeln("                                                        for (var i = 0; i < 4; i++) {");
document.writeln("                                                            var ranNum = Math.ceil(Math.random() * 25); //生成一个0到25的数字");
document.writeln("                                                            //大写字母\'A\'的ASCII是65,A~Z的ASCII码就是65 + 0~25;然后调用String.fromCharCode()传入ASCII值返回相应的字符并push进数组里");
document.writeln("                                                            result.push(String.fromCharCode(65 + ranNum));");
document.writeln("                                                        }");
document.writeln("                                                        document.getElementById(\'result\').innerText = result.toString();");
document.writeln("                                                        document.getElementById(\'result\').style.fontSize = \'24px\';");
document.writeln("                                                        document.getElementById(\'result\').style.fontFamily = \'楷体\';");
document.writeln("                                                        document.getElementById(\'result\').style.opacity = \'0.1\';");
document.writeln("                                                        document.getElementById(\'result\').style.lineHeight = \'30px\';");
document.writeln("                                                    }");
document.writeln("                                                </script>");
document.writeln("                                            </div>");
document.writeln("                                            <br>");
document.writeln("                                            <div class=\'inputs\'>");
document.writeln("                                                <label class=\'inputs_label1\'>短信验证</label>");
document.writeln("                                                <input id=\'iptDx\' class=\'inputs_input\' type=\'text\' />");
document.writeln("                                                <!-- 短信验证 -->");
document.writeln("                                                <div class=\'yzDx\'>");
document.writeln("                                                    <a id=\'button\'>");
document.writeln("                                                        <!-- 获取验证码 -->");
document.writeln("                                                    </a>");
document.writeln("                                                </div>");
document.writeln("                                                <p id=\'pDX\' style=\'font-size: 13px;\'>");
document.writeln("                                                    </span>");
document.writeln("                                            </div>");
document.writeln("                                            <script src=\'./js/daojishiYZM.js\'></script>");
document.writeln("");
document.writeln("                                            <!-- 记住我 -->");
document.writeln("                                            <div class=\'jz\'>");
document.writeln("                                                <input class=\'jizhu\' type=\'checkbox\' /> 记住我");
document.writeln("                                            </div>");
document.writeln("                                            <div class=\'divBtns\'>");
document.writeln("                                                <button class=\'buttons\'>登录</button>");
document.writeln("                                            </div>");
document.writeln("                                            <br />");
document.writeln("                                            <p class=\'txt1\'>即刻加入UA运动家俱乐部，开启您的专享会员礼遇:</p>");
document.writeln("                                            <div class=\'divTxt\'>");
document.writeln("                                                <ul class=\'divTxtUl\'>");
document.writeln("                                                    <li>会员优享商品特权</li>");
document.writeln("                                                    <li>第一时间获得新品资讯</li>");
document.writeln("                                                    <li>积分礼遇，享消费购物积分</li>");
document.writeln("                                                    <li>品牌专属俱乐部体验与活动</li>");
document.writeln("                                                    <li>更全面的售后服务</li>");
document.writeln("                                                </ul>");
document.writeln("                                            </div>");
document.writeln("                                        </div>");
document.writeln("                                    </form>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <!-- 登录 -->");
document.writeln("                            <div id=\'div2\'>");
document.writeln("                                <div id=\'div2_div1\'>");
document.writeln("                                    <!-- 点击x -->");
document.writeln("                                    <div id=\'xImg2\' class=\'div1_div11X\'><img src=\'image/x.png\' width=\'15\'></div>");
document.writeln("                                    <script>");
document.writeln("                                        $(function() {");
document.writeln("                                            var xImg2 = document.getElementById(\'xImg2\');");
document.writeln("                                            var yinyin = document.querySelector(\'.yinyin\');");
document.writeln("                                            xImg2.onclick = function() {");
document.writeln("                                                yinyin.style.display = \'none\';");
document.writeln("                                            }");
document.writeln("                                        })");
document.writeln("                                    </script>");
document.writeln("                                    <h4>欢迎来到<strong>UA</strong>运动家俱乐部</h4>");
document.writeln("");
document.writeln("                                    <ul class=\'div2_div1ul dialog-title-box e-switch\'>");
document.writeln("                                        <li onclick=\'TurnToRegister()\' class=\'div2_div1ulli1\'>");
document.writeln("                                            <a class=\'aP1\' style=\'font-size: 14px;\'>手机号快捷登录/注册</a>");
document.writeln("                                            <span class=\'hx3\'></span>");
document.writeln("                                        </li>");
document.writeln("                                        <li onclick=\'TurnToLogin()\' class=\'div2_div1ulli2\'>");
document.writeln("                                            <a style=\'color: #000000;font-size: 14px;\' class=\'aP2\'>账号密码登录</a>");
document.writeln("                                            <span class=\'hx4\'></span>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                    <!-- 登录表单 -->");
document.writeln("                                    <form id=\'myLoginForm\'>");
document.writeln("                                        <div class=\'divform\'>");
document.writeln("                                            <div class=\'inputs\'>");
document.writeln("                                                <label class=\'inputs_label1\'>手机号码/邮箱</label>");
document.writeln("                                                <input id=\'iptPhone2\' class=\'inputs_input\' type=\'text\' />");
document.writeln("                                                <p style=\'font-size: 13px;\' class=\'namess\' id=\'PPhone2\'></p>");
document.writeln("                                            </div>");
document.writeln("                                            <br />");
document.writeln("                                            <div class=\'inputs\'>");
document.writeln("                                                <label class=\'inputs_label1\'>密码</label>");
document.writeln("                                                <input id=\'pwd\' class=\'inputs_input\' type=\'password\' />");
document.writeln("                                                <p id=\'Ppwd\' style=\'font-size: 13px;\'></p>");
document.writeln("                                            </div>");
document.writeln("                                            <!-- 记住我 -->");
document.writeln("                                            <div class=\'jz2\'>");
document.writeln("                                                <p>");
document.writeln("                                                    <span>");
document.writeln("                                                        <input class=\'jizhu\' type=\'checkbox\' /> 记住我");
document.writeln("                                                    </span>");
document.writeln("                                                    <span class=\'wjPwd\'><a href=\'#\'>忘记密码?</a></span>");
document.writeln("                                                </p>");
document.writeln("                                            </div>");
document.writeln("                                            <div class=\'divBtns\'>");
document.writeln("                                                <button class=\'buttons\'>登录</button>");
document.writeln("                                            </div>");
document.writeln("                                            <br />");
document.writeln("                                            <p class=\'txt1\'>即刻加入UA运动家俱乐部，开启您的专享会员礼遇:</p>");
document.writeln("                                            <div class=\'divTxt\'>");
document.writeln("                                                <ul class=\'divTxtUl\'>");
document.writeln("                                                    <li>会员优享商品特权</li>");
document.writeln("                                                    <li>第一时间获得新品资讯</li>");
document.writeln("                                                    <li>积分礼遇，享消费购物积分</li>");
document.writeln("                                                    <li>品牌专属俱乐部体验与活动</li>");
document.writeln("                                                    <li>更全面的售后服务</li>");
document.writeln("                                                </ul>");
document.writeln("                                            </div>");
document.writeln("                                        </div>");
document.writeln("                                    </form>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <!-- 模态框 -->");
document.writeln("                        <script>");
document.writeln("                            var btn = document.getElementById(\'btn\');");
document.writeln("                            var yinyin = document.querySelector(\'.yinyin\');");
document.writeln("                            btn.onclick = function() {");
document.writeln("                                yinyin.style.display = \'block\';");
document.writeln("                            }");
document.writeln("                        </script>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <!-- 顶部菜单 -->");
document.writeln("            <div class=\'top-menu\'>");
document.writeln("                <!-- 左部logo -->");
document.writeln("                <div class=\'menu-left\'>");
document.writeln("                    <a href=\'home.html\'>");
document.writeln("                        <img src=\'img/header-logo.png\' alt=\'\' />");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <!-- 中部菜单栏 -->");
document.writeln("                <ul class=\'menu-tab\'>");
document.writeln("                    <li class=\'man\'>");
document.writeln("                        <ul class=\'menu-title\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'man.html\' class=\'lable1\' data-text=\'男子\'>男子</a>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'line\'></li>");
document.writeln("                        </ul>");
document.writeln("                        <div class=\'sub-menu\'>");
document.writeln("                            <ul class=\'nav-box\'>");
document.writeln("                                <li>");
document.writeln("                                    <img src=\'img/CN-HP-NAV-PC-0419-1.jpg\' alt=\'\' />");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\'>男子ISO-CHILL系列</a>");
document.writeln("                                    </p>");
document.writeln("                                    <p class=\'buy\'>");
document.writeln("                                        <a href=\'\' class=\'line2\'>即刻选购</a>");
document.writeln("                                    </p>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>推荐系列</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>男子新品推荐</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>男子ISO-CHILL系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>CURRY品牌</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>男子VELOCITI FLOW系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>男子PROJECT ROCK系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>男子CHARGED跑鞋系列</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>服装</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>短袖/背心</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>POLO衫</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>长袖</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>连帽上衣</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>外套</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>短裤</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>紧身裤</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>中裤</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>长裤</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>鞋类</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>跑鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>篮球鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>训练鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>运动休闲鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>拖鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>其他</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>配件</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul class=\'duan\'>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>运动耳机</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>包</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>帽</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>袜</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>手套</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>其他</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>运动</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>训练</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>跑步</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>篮球</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>高尔夫</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>户外</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>足球</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>运动休闲</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'women\'>");
document.writeln("                        <ul class=\'menu-title\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'women.html\' class=\'lable1\'>女子</a>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'line\'></li>");
document.writeln("                        </ul>");
document.writeln("                        <div class=\'sub-menu\'>");
document.writeln("                            <ul class=\'nav-box\'>");
document.writeln("                                <li>");
document.writeln("                                    <img src=\'img/CN-HP-NAV-PC-0419.jpg\' alt=\'\' />");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\'>女子ISO-CHILL系列</a>");
document.writeln("                                    </p>");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\' class=\'line2\'>即刻选购</a>");
document.writeln("                                    </p>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>推荐系列</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'New Products yao/newProducts.html\' class=\'line2\'>女子新品推荐</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>女子ISO-CHILL系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>CURRY品牌</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>女子VELOCITI FLOW系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>女子PROJECT ROCK系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>女子CHARGED跑鞋系列</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>服装</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>短袖/背心</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>POLO衫</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>长袖</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>连帽上衣</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>外套</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>短裤</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>紧身裤</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>中裤</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>长裤</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>连衣裙/短裙</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>鞋类</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>跑鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>篮球鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>训练鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>运动休闲鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>拖鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>其他</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>配件</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul class=\'duan\'>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>运动耳机</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>包</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>帽</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>袜</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>头带</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>手套</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>其他</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content duan\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>运动</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>训练</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>健身/瑜伽</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>跑步</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>户外</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>高尔夫</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>运动休闲</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'children\'>");
document.writeln("                        <ul class=\'menu-title\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'https://www.underarmour.cn/mens.htm#11\' class=\'lable1\'>少年</a>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'line\'></li>");
document.writeln("                        </ul>");
document.writeln("                        <div class=\'sub-menu\'>");
document.writeln("                            <ul class=\'nav-box\'>");
document.writeln("                                <li>");
document.writeln("                                    <img src=\'img/CN-NAV1-PC-HP-20210618.jpg\' alt=\'\' />");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\'>男童上装</a>");
document.writeln("                                    </p>");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\' class=\'line2\'>即刻选购</a>");
document.writeln("                                    </p>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>推荐系列</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>少年新品推荐</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>少年ROCK系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>少年HOVR系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>少年FLEECE抓绒系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>小童系列</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>男童装备</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul class=\'duan\'>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>上装</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>下装</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>鞋类</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>配件</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>女童装备</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul class=\'duan\'>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>上装</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>下装</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>鞋类</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>配件</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>运动</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul class=\'duan\'>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>跑步</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>训练</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>篮球</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'story\'>");
document.writeln("                        <ul class=\'menu-title\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'https://www.underarmour.cn/brandstory.htm#11\' class=\'lable1\'>品牌故事</a>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'line\'></li>");
document.writeln("                        </ul>");
document.writeln("                        <ul class=\'sub-menu\'>");
document.writeln("                            <ul>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'\'>");
document.writeln("                                        <img src=\'img/brandstory-1.jpg\' alt=\'\' />");
document.writeln("                                    </a>");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\'>关于品牌</a>");
document.writeln("                                    </p>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'\'>");
document.writeln("                                        <img src=\'img/brandstory-2.jpg\' alt=\'\' />");
document.writeln("                                    </a>");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\'>运动明星</a>");
document.writeln("                                    </p>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'\'>");
document.writeln("                                        <img src=\'img/brandstory-3.jpg\' alt=\'\' />");
document.writeln("                                    </a>");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\'>媒体中心</a>");
document.writeln("                                    </p>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("                <!-- 右部搜索栏 -->");
document.writeln("                <div class=\'menu-right\'>");
document.writeln("                    <div class=search-box>");
document.writeln("                        <input type=\'search\' maxlength=\'\' placeholder=\'搜索\' id=\'searchWordHeader\' value=\'\' autocomplete=\'off\'>");
document.writeln("                        <a href=\'\'>");
document.writeln("                            <span class=\'search-btn iconfont\'></span>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("                    <!-- 愿望单 -->");
document.writeln("                    <div class=\'wish-box\'>");
document.writeln("                        <a href=\'\'>");
document.writeln("                            <span class=\'wish-btn iconfont\'></span>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("                    <!-- 购物袋 -->");
document.writeln("                    <div class=\'shop-box\'>");
document.writeln("                        <!-- 遮罩层 -->");
document.writeln("                        <div class=\'shop-musk\'></div>");
document.writeln("                        <!-- 购物内容模块 -->");
document.writeln("                        <div class=\'shop-cont\'>");
document.writeln("                            <div class=\'car-close iconfont\'></div>");
document.writeln("                            <h4 class=\'car-title\'>购物袋 （0）</h4>");
document.writeln("                            <div class=\'shop-empty\'>");
document.writeln("                                您的购物袋为空");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <!-- 购物袋标志 -->");
document.writeln("                        <a href=\'\'>");
document.writeln("                            <span class=\'shop-btn iconfont\'></span>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </header>");
document.writeln("    <script src=\'jquery-1.11.3/jquery.min.js \'></script>");
document.writeln("    <script src=\'js/script.js\'></script>");
document.writeln("    <script src=\'js/home.js\'></script>");
document.writeln("    <script src=\'js/animate.js\'></script>");
document.writeln("    <script src=\'js/animate2.js\'></script>");
document.writeln("    <script src=\'js/register.js\'></script>");
document.writeln("    <script src=\'js/login.js\'></script>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");