document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>Document</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/home.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/font_search/iconfont.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/font_heart/iconfont.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/font_shop/iconfont.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/font_close/iconfont.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'css/font_arrow/iconfont.css\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <header>");
document.writeln("        <div class=\'header-box\'>");
document.writeln("            <!-- 顶部导航栏 -->");
document.writeln("            <div class=\'top-nav\'>");
document.writeln("                <div class=\'top-nav-left\'>");
document.writeln("                    <a href=\'\'>在线客服</a>");
document.writeln("                </div>");
document.writeln("                <div class=\'top-nav-right\'>");
document.writeln("                    <a href=\'\'>欢迎&nbsp;登录/注册</a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <!-- 顶部菜单 -->");
document.writeln("            <div class=\'top-menu\'>");
document.writeln("                <!-- 左部logo -->");
document.writeln("                <div class=\'menu-left\'>");
document.writeln("                    <a href=\'https://www.underarmour.cn/\'>");
document.writeln("                        <img src=\'img/header-logo.png\' alt=\'\' />");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <!-- 中部菜单栏 -->");
document.writeln("                <ul class=\'menu-tab\'>");
document.writeln("                    <li class=\'man\'>");
document.writeln("                        <ul class=\'menu-title\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'https://www.underarmour.cn/mens.htm#11\' class=\'lable1\' data-text=\'男子\'>男子</a>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'line\'></li>");
document.writeln("                        </ul>");
document.writeln("                        <div class=\'sub-menu\'>");
document.writeln("                            <ul class=\'nav-box\'>");
document.writeln("                                <li>");
document.writeln("                                    <img src=\'img/CN-HP-NAV-PC-0419-1.jpg\' alt=\'\' />");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\'>男子ISO-CHILL系列</a>");
document.writeln("                                    </p>");
document.writeln("                                    <p class=\'buy\'>");
document.writeln("                                        <a href=\'\' class=\'line2\'>即刻选购</a>");
document.writeln("                                    </p>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>推荐系列</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>男子新品推荐</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>男子ISO-CHILL系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>CURRY品牌</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>男子VELOCITI FLOW系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>男子PROJECT ROCK系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>男子CHARGED跑鞋系列</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>服装</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>短袖/背心</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>POLO衫</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>长袖</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>连帽上衣</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>外套</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>短裤</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>紧身裤</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>中裤</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>长裤</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>鞋类</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>跑鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>篮球鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>训练鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>运动休闲鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>拖鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>其他</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>配件</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul class=\'duan\'>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>运动耳机</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>包</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>帽</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>袜</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>手套</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>其他</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>运动</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>训练</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>跑步</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>篮球</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>高尔夫</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>户外</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>足球</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>运动休闲</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'women\'>");
document.writeln("                        <ul class=\'menu-title\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'https://www.underarmour.cn/mens.htm#11\' class=\'lable1\'>女子</a>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'line\'></li>");
document.writeln("                        </ul>");
document.writeln("                        <div class=\'sub-menu\'>");
document.writeln("                            <ul class=\'nav-box\'>");
document.writeln("                                <li>");
document.writeln("                                    <img src=\'img/CN-HP-NAV-PC-0419.jpg\' alt=\'\' />");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\'>女子ISO-CHILL系列</a>");
document.writeln("                                    </p>");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\' class=\'line2\'>即刻选购</a>");
document.writeln("                                    </p>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>推荐系列</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>女子新品推荐</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>女子ISO-CHILL系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>CURRY品牌</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>女子VELOCITI FLOW系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>女子PROJECT ROCK系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>女子CHARGED跑鞋系列</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>服装</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>短袖/背心</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>POLO衫</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>长袖</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>连帽上衣</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>外套</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>短裤</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>紧身裤</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>中裤</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>长裤</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>连衣裙/短裙</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>鞋类</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>跑鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>篮球鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>训练鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>运动休闲鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>拖鞋</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>其他</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>配件</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul class=\'duan\'>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>运动耳机</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>包</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>帽</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>袜</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>头带</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>手套</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>其他</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content duan\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>运动</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>训练</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>健身/瑜伽</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>跑步</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>户外</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>高尔夫</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>运动休闲</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'children\'>");
document.writeln("                        <ul class=\'menu-title\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'https://www.underarmour.cn/mens.htm#11\' class=\'lable1\'>少年</a>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'line\'></li>");
document.writeln("                        </ul>");
document.writeln("                        <div class=\'sub-menu\'>");
document.writeln("                            <ul class=\'nav-box\'>");
document.writeln("                                <li>");
document.writeln("                                    <img src=\'img/CN-NAV1-PC-HP-20210618.jpg\' alt=\'\' />");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\'>男童上装</a>");
document.writeln("                                    </p>");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\' class=\'line2\'>即刻选购</a>");
document.writeln("                                    </p>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>推荐系列</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>少年新品推荐</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>少年ROCK系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>少年HOVR系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>少年FLEECE抓绒系列</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>小童系列</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>男童装备</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul class=\'duan\'>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>上装</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>下装</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>鞋类</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>配件</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>女童装备</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul class=\'duan\'>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>上装</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>下装</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>鞋类</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>配件</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <ul class=\'nav-box-content\'>");
document.writeln("                                        <li>");
document.writeln("                                            <p class=\'line2\'>");
document.writeln("                                                <a href=\'\'>运动</a>");
document.writeln("                                            </p>");
document.writeln("                                            <ul class=\'duan\'>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>跑步</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>训练</a>");
document.writeln("                                                </li>");
document.writeln("                                                <li>");
document.writeln("                                                    <a href=\'\' class=\'line2\'>篮球</a>");
document.writeln("                                                </li>");
document.writeln("                                            </ul>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'story\'>");
document.writeln("                        <ul class=\'menu-title\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'https://www.underarmour.cn/brandstory.htm#11\' class=\'lable1\'>品牌故事</a>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'line\'></li>");
document.writeln("                        </ul>");
document.writeln("                        <ul class=\'sub-menu\'>");
document.writeln("                            <ul>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'\'>");
document.writeln("                                        <img src=\'img/brandstory-1.jpg\' alt=\'\' />");
document.writeln("                                    </a>");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\'>关于品牌</a>");
document.writeln("                                    </p>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'\'>");
document.writeln("                                        <img src=\'img/brandstory-2.jpg\' alt=\'\' />");
document.writeln("                                    </a>");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\'>运动明星</a>");
document.writeln("                                    </p>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'\'>");
document.writeln("                                        <img src=\'img/brandstory-3.jpg\' alt=\'\' />");
document.writeln("                                    </a>");
document.writeln("                                    <p>");
document.writeln("                                        <a href=\'\'>媒体中心</a>");
document.writeln("                                    </p>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("                <!-- 右部搜索栏 -->");
document.writeln("                <div class=\'menu-right\'>");
document.writeln("                    <div class=search-box>");
document.writeln("                        <input type=\'search\' maxlength=\'\' placeholder=\'搜索\' id=\'searchWordHeader\' value=\'\' autocomplete=\'off\'>");
document.writeln("                        <a href=\'\'>");
document.writeln("                            <span class=\'search-btn iconfont\'></span>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("                    <!-- 愿望单 -->");
document.writeln("                    <div class=\'wish-box\'>");
document.writeln("                        <a href=\'\'>");
document.writeln("                            <span class=\'wish-btn iconfont\'></span>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("                    <!-- 购物袋 -->");
document.writeln("                    <div class=\'shop-box\'>");
document.writeln("                        <!-- 遮罩层 -->");
document.writeln("                        <div class=\'shop-musk\'></div>");
document.writeln("                        <!-- 购物内容模块 -->");
document.writeln("                        <div class=\'shop-cont\'>");
document.writeln("                            <div class=\'car-close iconfont\'></div>");
document.writeln("                            <h4 class=\'car-title\'>购物袋 （0）</h4>");
document.writeln("                            <div class=\'shop-empty\'>");
document.writeln("                                您的购物袋为空");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <!-- 购物袋标志 -->");
document.writeln("                        <a href=\'\'>");
document.writeln("                            <span class=\'shop-btn iconfont\'></span>");
document.writeln("                        </a>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </header>");
document.writeln("    <script src=\'js/jquery.min.js \'></script>");
document.writeln("    <script src=\'js/script.js\'></script>");
document.writeln("    <script src=\'js/home.js\'></script>");
document.writeln("    <script src=\'js/animate.js\'></script>");
document.writeln("    <script src=\'js/animate2.js\'></script>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");