document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>Document</title>");
document.writeln("   ");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <footer>");
document.writeln("        <div class=\'foot1\'>");
document.writeln("            <p>没有找到你想要的？</p>");
document.writeln("            <div class=\'foot1-search\'>");
document.writeln("                <input type=\'text\' /><span class=\'search-btn iconfont\'></span>");
document.writeln("            </div>");
document.writeln("            <div class=\'foot1-search-sugges\'>");
document.writeln("                <span>试试搜索</span>");
document.writeln("                <span><a href=\'\'>直降专区</a></span>");
document.writeln("                <span><a href=\'\'>CURRY8 篮球鞋</a></span>");
document.writeln("                <span><a href=\'\'>ISO-CHILL系列</a></span>");
document.writeln("                <span><a href=\'\'>PROJECT ROCK系列</a></span>");
document.writeln("                <span><a href=\'\'>VELOCITI FLOW系列</a></span>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'foot2\'>");
document.writeln("            <div class=\'foot2-box\'>");
document.writeln("                <div class=\'foot2-top\'>");
document.writeln("                    <div class=\'foot2-top-left\'>");
document.writeln("                        <div class=\'foot2-logo\'>");
document.writeln("                            <a href=\'\'></a>");
document.writeln("                        </div>");
document.writeln("                        <p class=\'foot2-title1\'>获取 UA 最新资讯</p>");
document.writeln("                        <div class=\'foot2-email\'>");
document.writeln("                            <input type=\'email\' name=\'\' id=\'\'>");
document.writeln("                            <div class=\'foot2-shu\'>");
document.writeln("                                <p>请输入电子邮箱</p>");
document.writeln("                            </div>");
document.writeln("                            <div>");
document.writeln("                                <a href=\'\'>订阅</a>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <p class=\'foot2-title2\'>关注我们</p>");
document.writeln("                        <ul class=\'foot2-flow\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'\'></a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'\'></a>");
document.writeln("                                <img src=\'img/wechat-pc.jpg\' alt=\'\' />");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                    <ul class=\'foot2-ua-concat\'>");
document.writeln("                        <li>联系方式</li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>");
document.writeln("                                <span class=\'foot2-phone\'></span>");
document.writeln("                                <span>4008-206-528</span>");
document.writeln("                            </a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>");
document.writeln("                                <span class=\'foot2-message\'></span>");
document.writeln("                                <span>在线客服</span>");
document.writeln("                            </a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>");
document.writeln("                                <span class=\'foot2-place\'></span>");
document.writeln("                                <span>线下门店</span>");
document.writeln("                            </a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                    <ul class=\'foot2-ua-concat\'>");
document.writeln("                        <li>客户服务</li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>会员政策</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>尺码剪裁说明</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>联系我们</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>加入我们</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>大客户团购</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>礼品卡使用章程</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                    <ul class=\'foot2-ua-concat\'>");
document.writeln("                        <li>订单及售后</li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>游客订单查询</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>支付说明</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>物流与配送</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>退换货政策说明</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>公告</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                    <ul class=\'foot2-ua-concat\'>");
document.writeln("                        <li>品牌故事</li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>关于品牌 </a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>运动明星</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href=\'\'>媒体中心</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <ul class=\'foot2-bottom\'>");
document.writeln("                    <li>");
document.writeln("                        Copyright ©2021 Under Armour, Inc.");
document.writeln("                    </li>");
document.writeln("                    <li class=\'divider\'></li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>隐私政策</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'divider\'></li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>使用规则</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'divider\'></li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>网站地图</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'divider\'></li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\'>沪ICP备12034417号-1</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'divider\'></li>");
document.writeln("                    <li>");
document.writeln("                        <span class=\'foot2-dz\'></span>");
document.writeln("                        <a href=\'\'>电子营业执照</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'divider\'></li>");
document.writeln("                    <li>");
document.writeln("                        <span class=\'foot2-hg\'></span>");
document.writeln("                        <a href=\'\'>沪公网安备 31010102003916号</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div id=\'toTop\'>");
document.writeln("");
document.writeln("        </div>");
document.writeln("    </footer>");
document.writeln("   ");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");